INCLUDED_CURRENCIES = [
    'Afghan Afghani',
    'Albanian Lek',
    'Algerian Dinar',
    'Andorran Peseta',
    'Angolan Kwanza',
    'Argentine Austral',
    'Argentine Peso',
    'Armenian Dram',
    'Aruban Florin',
    'Australian Dollar',
    'Austrian Schilling',
    'Azerbaijani Manat',
    'Bahamian Dollar',
    'Bahraini Dinar',
    'Bangladeshi Taka',
    'Barbadian Dollar',
    'Belarusian Ruble',
    'Belgian Franc',
    'Belize Dollar',
    'Bermudan Dollar',
    'Bhutanese Ngultrum',
    'Bolivian Boliviano',
    'Bolivian Mvdol',
    'Bolivian Peso',
    'Bolívar Soberano',
    'Bosnia-Herzegovina Convertible Mark',
    'Botswanan Pula',
    'Brazilian Real',
    'British Pound',
    'Brunei Dollar',
    'Bulgarian Hard Lev',
    'Bulgarian Lev',
    'Bulgarian Socialist Lev',
    'Burmese Kyat',
    'Burundian Franc',
    'CFP Franc',
    'Cambodian Riel',
    'Canadian Dollar',
    'Cape Verdean Escudo',
    'Cayman Islands Dollar',
    'Central African CFA Franc',
    'Chilean Peso',
    'Chinese Yuan',
    'Colombian Peso',
    'Comorian Franc',
    'Congolese Franc',
    'Costa Rican Colón',
    'Croatian Kuna',
    'Cuban Peso',
    'Cypriot Pound',
    'Czech Koruna',
    'Danish Krone',
    'Djiboutian Franc',
    'Dominican Peso',
    'Dutch Guilder',
    'East Caribbean Dollar',
    'East German Mark',
    'Ecuadorian Sucre',
    'Ecuadorian Unit of Constant Value',
    'Egyptian Pound',
    'Equatorial Guinean Ekwele',
    'Eritrean Nakfa',
    'Estonian Kroon',
    'Ethiopian Birr',
    'Euro',
    'Falkland Islands Pound',
    'Fijian Dollar',
    'Finnish Markka',
    'French Franc',
    'Gambian Dalasi',
    'Georgian Lari',
    'German Mark',
    'Ghanaian Cedi',
    'Gibraltar Pound',
    'Gold',
    'Greek Drachma',
    'Guatemalan Quetzal',
    'Guinea-Bissau Peso',
    'Guinean Franc',
    'Guyanaese Dollar',
    'Haitian Gourde',
    'Honduran Lempira',
    'Hong Kong Dollar',
    'Hungarian Forint',
    'Icelandic Króna',
    'Indian Rupee',
    'Indonesian Rupiah',
    'Iranian Rial',
    'Iraqi Dinar',
    'Irish Pound',
    'Isle of Man',
    'Israeli New Shekel',
    'Italian Lira',
    'Jamaican Dollar',
    'Japanese Yen',
    'Jordanian Dinar',
    'Kazakhstani Tenge',
    'Kenyan Shilling',
    'Kuwaiti Dinar',
    'Kyrgystani Som',
    'Laotian Kip',
    'Latvian Lats',
    'Lebanese Pound',
    'Lesotho Loti',
    'Liberian Dollar',
    'Libyan Dinar',
    'Lithuanian Litas',
    'Luxembourgian Franc',
    'Macanese Pataca',
    'Macedonian Denar',
    'Malagasy Ariary',
    'Malawian Kwacha',
    'Malaysian Ringgit',
    'Maldivian Rufiyaa',
    'Malian Franc',
    'Maltese Lira',
    'Mauritanian Ouguiya',
    'Mauritian Rupee',
    'Mexican Peso',
    'Moldovan Cupon',
    'Moldovan Leu',
    'Monegasque Franc',
    'Mongolian Tugrik',
    'Moroccan Dirham',
    'Mozambican Escudo',
    'Mozambican Metical',
    'Myanmar Kyat',
    'Namibian Dollar',
    'Nepalese Rupee',
    'Netherlands Antillean Guilder',
    'New Taiwan Dollar',
    'New Zealand Dollar',
    'Nicaraguan Córdoba',
    'Nigerian Naira',
    'North Korean Won',
    'Norwegian Krone',
    'Omani Rial',
    'Pakistani Rupee',
    'Palladium',
    'Panamanian Balboa',
    'Papua New Guinean Kina',
    'Paraguayan Guarani',
    'Peruvian Sol',
    'Philippine Peso',
    'Platinum Ounces',
    'Polish Zloty',
    'Portuguese Escudo',
    'Qatari Riyal',
    'Romanian Leu',
    'Russian Ruble',
    'Rwandan Franc',
    'Salvadoran Colón',
    'Samoan Tala',
    'Saudi Riyal',
    'Serbian Dinar',
    'Seychellois Rupee',
    'Sierra Leonean Leone',
    'Singapore Dollar',
    'Slovak Koruna',
    'Slovenian Tolar',
    'Solomon Islands Dollar',
    'Somali Shilling',
    'South African Rand',
    'South Korean Won',
    'South Sudanese Pound',
    'Soviet Rouble',
    'Spanish Peseta',
    'Sri Lankan Rupee',
    'St. Helena Pound',
    'Sucre',
    'Sudanese Pound',
    'Surinamese Dollar',
    'Surinamese Guilder',
    'Swazi Lilangeni',
    'Swedish Krona',
    'Swiss Franc',
    'Syrian Pound',
    'São Tomé & Príncipe Dobra',
    'TVD',
    'Tajikistani Somoni',
    'Tanzanian Shilling',
    'Thai Baht',
    'Timorese Escudo',
    'Tongan Paʻanga',
    'Trinidad & Tobago Dollar',
    'Tunisian Dinar',
    'Turkish Lira',
    'Turkmenistani Manat',
    'US Dollar',
    'Ugandan Shilling',
    'Ukrainian Hryvnia',
    'Ukrainian Karbovanets',
    'United Arab Emirates Dirham',
    'Uruguayan Peso',
    'Uzbekistani Som',
    'Vanuatu Vatu',
    'Venezuelan Bolívar',
    'Vietnamese Dong',
    'West African CFA Franc',
    'Yemeni Dinar',
    'Yemeni Rial',
    'ZWN',
    'Zambian Kwacha'
]


INCLUDED_CURRENCIES = (
    'AFN',
    'ALL',
    'DZD',
    'ADP',
    'AOA',
    'ARA',
    'ARS',
    'AMD',
    'AWG',
    'AUD',
    'ATS',
    'AZN',
    'BSD',
    'BHD',
    'BDT',
    'BBD',
    'BYN',
    'BEF',
    'BZD',
    'BMD',
    'BTN',
    'BOB',
    'BOV',
    'BOP',
    'VED',
    'BAM',
    'BWP',
    'BRL',
    'GBP',
    'BND',
    'BGL',
    'BGN',
    'BGM',
    'BUK',
    'BIF',
    'XPF',
    'KHR',
    'CAD',
    'CVE',
    'KYD',
    'XAF',
    'CLP',
    'CNY',
    'COP',
    'KMF',
    'CDF',
    'CRC',
    'HRK',
    'CUP',
    'CYP',
    'CZK',
    'DKK',
    'DJF',
    'DOP',
    'NLG',
    'XCD',
    'DDM',
    'ECS',
    'ECV',
    'EGP',
    'GQE',
    'ERN',
    'EEK',
    'ETB',
    'EUR',
    'FKP',
    'FJD',
    'FIM',
    'FRF',
    'GMD',
    'GEL',
    'DEM',
    'GHS',
    'GIP',
    'XAU',
    'GRD',
    'GTQ',
    'GWP',
    'GNF',
    'GYD',
    'HTG',
    'HNL',
    'HKD',
    'HUF',
    'ISK',
    'INR',
    'IDR',
    'IRR',
    'IQD',
    'IEP',
    'IMP',
    'ILS',
    'ITL',
    'JMD',
    'JPY',
    'JOD',
    'KZT',
    'KES',
    'KWD',
    'KGS',
    'LAK',
    'LVL',
    'LBP',
    'LSL',
    'LRD',
    'LYD',
    'LTL',
    'LUF',
    'MOP',
    'MKD',
    'MGA',
    'MWK',
    'MYR',
    'MVR',
    'MLF',
    'MTL',
    'MRU',
    'MUR',
    'MXN',
    'MDC',
    'MDL',
    'MCF',
    'MNT',
    'MAD',
    'MZE',
    'MZN',
    'MMK',
    'NAD',
    'NPR',
    'ANG',
    'TWD',
    'NZD',
    'NIO',
    'NGN',
    'KPW',
    'NOK',
    'OMR',
    'PKR',
    'XPD',
    'PAB',
    'PGK',
    'PYG',
    'PEN',
    'PHP',
    'XPT',
    'PLN',
    'PTE',
    'QAR',
    'RON',
    'RUB',
    'RWF',
    'SVC',
    'WST',
    'SAR',
    'RSD',
    'SCR',
    'SLE',
    'SGD',
    'SKK',
    'SIT',
    'SBD',
    'SOS',
    'ZAR',
    'KRW',
    'SSP',
    'SUR',
    'ESP',
    'LKR',
    'SHP',
    'XSU',
    'SDG',
    'SRD',
    'SRG',
    'SZL',
    'SEK',
    'CHF',
    'SYP',
    'STN',
    'TVD',
    'TJS',
    'TZS',
    'THB',
    'TPE',
    'TOP',
    'TTD',
    'TND',
    'TRY',
    'TMT',
    'USD',
    'UGX',
    'UAH',
    'UAK',
    'AED',
    'UYU',
    'UZS',
    'VUV',
    'VES',
    'VND',
    'XOF',
    'YDD',
    'YER',
    'ZWN',
    'ZMW'
)